### ISSUE TITLE
Says No Active Users Found

### ISSUE THREAD

**Issue by amandesai01** [ayushjainrksh/conactivity#41]
**Describe the bug**
When I run the script, It says no active users found on page 0. Although, there are users listed. I used `process.env.company` as `Google`

**Console Logs**
```
DevTools listening on ws://127.0.0.1:57518/devtools/browser/bf2b62bf-8ce0-41ff-aac9-419958394897
Previous session loaded successfully!
[38436:775:1002/184946.651985:ERROR:device_event_log_impl.cc(208)] [18:49:46.651] FIDO: touch_id_context.mm:125 Touch ID authenticator unavailable because keychain-access-group entitlement is missing or incorrect
[38453:50951:1002/184959.974540:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"FFmpegDemuxer: no supported streams"}
[38453:775:1002/184959.986721:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":14}
Active users on page 0:  []
2020-10-02 18:50:45.398 Chromium Helper (Renderer)[38453:12184431] CoreText note: Client requested name ".PingFangSC-Medium", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-10-02 18:50:45.398 Chromium Helper (Renderer)[38453:12184431] CoreText note: Set a breakpoint on CTFontLogSystemFontNameRequest to debug.
2020-10-02 18:50:45.409 Chromium Helper (Renderer)[38453:12184431] CoreText note: Client requested name ".PingFangSC-Medium", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-10-02 18:50:45.410 Chromium Helper (Renderer)[38453:12184431] CoreText note: Client requested name ".PingFangSC-Medium", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-10-02 18:50:45.411 Chromium Helper (Renderer)[38453:12184431] CoreText note: Client requested name ".PingFangSC-Medium", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-10-02 18:50:45.461 Chromium Helper (Renderer)[38453:12184431] CoreText note: Client requested name ".AppleSDGothicNeoI-SemiBold", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-10-02 18:50:45.468 Chromium Helper (Renderer)[38453:12184431] CoreText note: Client requested name ".PingFangSC-Medium", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-10-02 18:50:45.496 Chromium Helper (Renderer)[38453:12184431] CoreText note: Client requested name ".PingFangSC-Medium", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-10-02 18:50:45.497 Chromium Helper (Renderer)[38453:12184431] CoreText note: Client requested name ".PingFangSC-Medium", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-10-02 18:50:45.501 Chromium Helper (Renderer)[38453:12184431] CoreText note: Client requested name ".PingFangSC-Medium", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
2020-10-02 18:50:45.510 Chromium Helper (Renderer)[38453:12184431] CoreText note: Client requested name ".PingFangSC-Medium", it will get Times-Roman rather than the intended font. All system UI font access should be through proper APIs such as CTFontCreateUIFontForLanguage() or +[NSFont systemFontOfSize:].
[38453:50951:1002/185051.643056:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"FFmpegDemuxer: no supported streams"}
[38453:775:1002/185051.714533:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":14}
[38453:50951:1002/185051.719896:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"FFmpegDemuxer: no supported streams"}
[38453:775:1002/185051.775038:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":14}
[38453:50951:1002/185051.887375:ERROR:batching_media_log.cc(38)] MediaEvent: {"error":"FFmpegDemuxer: no supported streams"}
[38453:775:1002/185051.888243:ERROR:batching_media_log.cc(35)] MediaEvent: {"pipeline_error":14}
^Cnpm ERR! code ELIFECYCLE
npm ERR! errno 130
npm ERR! linkedin-scraper@1.0.0 start: `node scrape.js`
npm ERR! Exit status 130
npm ERR! 
npm ERR! Failed at the linkedin-scraper@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/aman/.npm/_logs/2020-10-02T13_20_59_693Z-debug.log
```

**To Reproduce**
Set `COMPANY=Google` in `.env` file. and run as directed in README.

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by ayushjainrksh** [comment]
@amandesai01 That's strange. I tested the script and it works fine. I saw your PR #40 has been made from the master branch. It is possible that the problem was introduced by the changes that you made in the PR. As a preliminary test, can you try making a fresh clone of the repo and rerun the script on the master branch if possible? If there's no output even on the fresh clone, please test if the selectors are working fine. If you find the solution, feel free to make a PR!

**Comment by amandesai01** [comment]
Hey @ayushjainrksh . That was the same thing which I thought. So I checked out to version at which master was before me making changes. Still found same error.

**Comment by amandesai01** [comment]
![Screenshot 2020-10-02 at 9 01 25 PM](https://user-images.githubusercontent.com/39585600/94941384-7109da80-04f2-11eb-94b3-d53cf712dd75.png)
 Here is a screenshot of me checking out to previous version. Checkout commit checksum to verify which version causes error.

Reverted to commit `83c3c40fdbe8d88679eca637f018fabacf14bdf2`

**Comment by ayushjainrksh** [comment]
@amandesai01 Okay thanks for confirming. Let me know if you find the problem. I'll also have a look.

**Comment by ayushjainrksh** [comment]
I checked again, it still works for me but I'm not surprised that it doesn't work for you. In the end, I'll need your help to figure this out. Might be a similar problem as #20

**Comment by ayushjainrksh** [comment]
@amandesai01 This issue should probably be fixed by #42. Please let me know if it works so that this issue can be closed.

**Comment by amandesai01** [comment]
@ayushjainrksh It still isn't working. I guess it is problem related to MacBook. I suspect this due to following line:
```
[38436:775:1002/184946.651985:ERROR:device_event_log_impl.cc(208)] [18:49:46.651] FIDO: touch_id_context.mm:125 Touch ID authenticator unavailable because keychain-access-group entitlement is missing or incorrect
```
KeyChain is a **password managing service** used by macOS to keep password management centralised and sync passwords across devices securely.

**Comment by ayushjainrksh** [comment]
@amandesai01 Thanks for reporting this issue. Please open a PR if you find a solution.
